#pragma once

//#define SERIAL_USART_SPEED 921600
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN B10
#define SERIAL_USART_RX_PIN B11
#define SERIAL_USART_PIN_SWAP
#define USART3_REMAP
#define SERIAL_USART_TX_PAL_MODE 4
#define SERIAL_USART_RX_PAL_MODE 4
#define SERIAL_USART_DRIVER SD3