#pragma once

#include_next <mcuconf.h>

#undef STM32_SERIAL_USE_USART3
#define STM32_SERIAL_USE_USART3 TRUE

#undef STM32_I2C_USE_I2C2
#define STM32_I2C_USE_I2C2 TRUE

#undef STM32_I2C_USE_DMA
#define STM32_I2C_USE_DMA FALSE

// #undef STM32_I2C_BUSY_TIMEOUT
// #define STM32_I2C_BUSY_TIMEOUT 50

// #undef STM32_I2C_XXX_IRQ_PRIORITY
// #define STM32_I2C_XXX_IRQ_PRIORITY 5

// #undef STM32_I2C_XXX_DMA_PRIORITY
// #define STM32_I2C_XXX_DMA_PRIORITY 1